### ISSUE TITLE
Is there a way to add it as a standalone library

### ISSUE THREAD

**Issue by nag9329** [kennethkalmer/ember-cli-nouislider#46]
Hi,

I have restrictions to use this module by ember install command. Is there a way I can copy the library into my project and use it?

Thanks!!!

**Comment by kennethkalmer** [comment]
Hi

I'm really curious as to why you can't use ember-cli, please let me know why it isn't possible.

That said, here is what you could do, **but I strongly discourage you from doing this**. This is completely unsupported by myself and the Ember community at large... The community has settled on the way it does things for a reason, please understand that.

That said, this addon is only really one component, and one dependency.

Firstly, the dependency. You can add the nouislider dependency to your `bower.json` or `package.json` files, but this also needs the same network access as ember-cli. So you'll need to download the dependency directly from https://refreshless.com/nouislider/ and include it in your project.

Then you could simply copy `addon/components/range-slider.js` into your own project and that should sort you out.

Again, I cannot **stress enough how this badly affects your ability to develop Ember apps** without being able to use ember-cli. The whole ecosystem is built around your ability, and the ability of your team, to use this tool.

Maybe what you're asking for sounds reasonable now, but what happens when you can't copy files into your project anymore? What happens when you're using 20 addons? What happens when an addon has its own dependencies? What happens when you hand the project over and it doesn't look like any other Ember project? This is a rabbithole that **only ends in despair**.

The real solution is to use ember-cli the way it was intended, and to work with your obstacles to get them removed.

Hope that makes sense.

**Comment by nag9329** [comment]
hey @kennethkalmer thanks for your response. 

Firstly, to clarify why I'm trying to include this as a standalone is Our company has to  vet the add on before we use it. Since, I'm trying to figure whether the add on can meet our requirements. So, I want to see how the add-on behaves before even I try to request for vetting process.

Secondly, I tried to include the add-on as standalone by downloading the file from the url you gave. But, I'm getting the following error testAppNouislider.default.create is not a function. 
        Here, testApp is my project name and the way I've included in the project is I copied the entire folder (consisting nouislider.js) I got from downloading the url you gave. I also copied the range-slider.js file into my components folder in my ember app. 

I don't know where I'm doing wrong. Any help to make this add-on useable in the way I'm trying  would be a lot helpful to me.

Thanks!!!

**Comment by kennethkalmer** [comment]
Hi @nag9329 

A few things come to mind:

* Create a new ember project, and play with it
* It is an open source project on GitHub, it can be vetted right from here
* Create a new branch in your project and integrate the addon and then ask your peers to review the branch. If it doesn't work, delete the branch and carry on like nothing happened.

I simply cannot support what you're asking as it doesn't make any sense whatsoever to have this amount of ceremony around each and every addon you're using. Following the same argument, was Ember itself also vetted? Was each of Ember's dependencies and their dependencies vetted?

See what I mean? This type of thinking has no end...

My apologies for this. I would really suggest you rather spend the effort on changing the process and end up better for it than copying files from GitHub.

Good luck!
